/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.ConsumptionModelScope
import de.bund.bfr.metadata.swagger.GenericModelDataBackground
import de.bund.bfr.metadata.swagger.Model
import de.bund.bfr.metadata.swagger.PredictiveModelGeneralInformation
import de.bund.bfr.metadata.swagger.PredictiveModelModelMath

/**
 * 
 * @param modelType 
 * @param generalInformation 
 * @param scope 
 * @param dataBackground 
 * @param modelMath 
 */
data class ConsumptionModel (

    val modelType: kotlin.String,
    val generalInformation: PredictiveModelGeneralInformation? = null,
    val scope: ConsumptionModelScope? = null,
    val dataBackground: GenericModelDataBackground? = null,
    val modelMath: PredictiveModelModelMath? = null
) {
}