/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param title 
 * @param familyName 
 * @param givenName 
 * @param email 
 * @param telephone 
 * @param streetAddress 
 * @param country 
 * @param zipCode 
 * @param region 
 * @param timeZone 
 * @param gender 
 * @param note 
 * @param organization 
 */
data class Contact (

    val title: kotlin.String? = null,
    val familyName: kotlin.String? = null,
    val givenName: kotlin.String? = null,
    val email: kotlin.String,
    val telephone: kotlin.String? = null,
    val streetAddress: kotlin.String? = null,
    val country: kotlin.String? = null,
    val zipCode: kotlin.String? = null,
    val region: kotlin.String? = null,
    val timeZone: kotlin.String? = null,
    val gender: kotlin.String? = null,
    val note: kotlin.String? = null,
    val organization: kotlin.String? = null
) {
}