/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param collectionTool Food diaries, interview, 24-hour recall interview, food propensy questionnaire, portion size measurement aids, eating outside questionnaire
 * @param numberOfNonConsecutiveOneDay Number of non-consecutive one-day recorded
 * @param softwareTool Name of the software used to collect the data
 * @param numberOfFoodItems Number of food items
 * @param recordTypes Consumption occasion, mean of consumption, quantified and described as eaten, recipes for self-made
 * @param foodDescriptors Description using FoodEx2 facet
 */
data class DietaryAssessmentMethod (

    /* Food diaries, interview, 24-hour recall interview, food propensy questionnaire, portion size measurement aids, eating outside questionnaire */
    val collectionTool: kotlin.String,
    /* Number of non-consecutive one-day recorded */
    val numberOfNonConsecutiveOneDay: kotlin.String,
    /* Name of the software used to collect the data */
    val softwareTool: kotlin.String? = null,
    /* Number of food items */
    val numberOfFoodItems: kotlin.Array<kotlin.String>,
    /* Consumption occasion, mean of consumption, quantified and described as eaten, recipes for self-made */
    val recordTypes: kotlin.Array<kotlin.String>,
    /* Description using FoodEx2 facet */
    val foodDescriptors: kotlin.Array<kotlin.String>
) {
}