/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.DoseResponseModelGeneralInformation
import de.bund.bfr.metadata.swagger.DoseResponseModelModelMath
import de.bund.bfr.metadata.swagger.DoseResponseModelScope
import de.bund.bfr.metadata.swagger.Model
import de.bund.bfr.metadata.swagger.PredictiveModelDataBackground

/**
 * 
 * @param modelType 
 * @param generalInformation 
 * @param scope 
 * @param dataBackground 
 * @param modelMath 
 */
data class DoseResponseModel (

    val modelType: kotlin.String,
    val generalInformation: DoseResponseModelGeneralInformation? = null,
    val scope: DoseResponseModelScope? = null,
    val dataBackground: PredictiveModelDataBackground? = null,
    val modelMath: DoseResponseModelModelMath? = null
) {
}