/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param treatment Description of the mathematical method to replace left-censored data (recommandation of WHO (2013), distribution or others)
 * @param contamination Description of the range of of the level of contamination after left censored data treatment
 * @param type Description of the type of exposure
 * @param scenario Description of the different scenarii used in exposure assessment
 * @param uncertaintyEstimation Analysis to estimate uncertainty
 */
data class Exposure (

    /* Description of the mathematical method to replace left-censored data (recommandation of WHO (2013), distribution or others) */
    val treatment: kotlin.Array<kotlin.String>? = null,
    /* Description of the range of of the level of contamination after left censored data treatment */
    val contamination: kotlin.Array<kotlin.String>? = null,
    /* Description of the type of exposure */
    val type: kotlin.String,
    /* Description of the different scenarii used in exposure assessment */
    val scenario: kotlin.Array<kotlin.String>? = null,
    /* Analysis to estimate uncertainty */
    val uncertaintyEstimation: kotlin.String? = null
) {
}