/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Hazard
import de.bund.bfr.metadata.swagger.PopulationGroup
import de.bund.bfr.metadata.swagger.Product

/**
 * 
 * @param product 
 * @param hazard 
 * @param populationGroup 
 * @param generalComment 
 * @param temporalInformation General comments on the scope of the study, data or model
 * @param spatialInformation Spatial information (area) on which the model or data applies
 */
data class GenericModelScope (

    val product: kotlin.Array<Product>? = null,
    val hazard: kotlin.Array<Hazard>? = null,
    val populationGroup: kotlin.Array<PopulationGroup>? = null,
    val generalComment: kotlin.String? = null,
    /* General comments on the scope of the study, data or model */
    val temporalInformation: kotlin.String? = null,
    /* Spatial information (area) on which the model or data applies */
    val spatialInformation: kotlin.Array<kotlin.String>? = null
) {
}