/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Contact
import de.bund.bfr.metadata.swagger.ModelCategory
import de.bund.bfr.metadata.swagger.Reference

/**
 * 
 * @param name A name given to the model or data
 * @param source A source from which the model/data is derived
 * @param identifier An unambiguous ID given to the model or data. This can also be created automatically by a software tool
 * @param author Person(s) who generated the model code or generated the data set originally
 * @param creator The person(s) that created this FSK file including all metadata
 * @param creationDate Creation date/time of the FSK file
 * @param modificationDate Date/time of the last version of the FSK file
 * @param rights Rights granted for usage, distribution and modification of this FSK file
 * @param availability Availability of data or model, i.e. if the annotated model code / data is included in this FSK file
 * @param url Web address referencing the resource location (data for example)
 * @param format File extension of the model or data file (including version number of format if applicable)
 * @param reference 
 * @param language A language of the resource (some data or reports can be available in French language for example)
 * @param software The program or software language in which the model has been implemented
 * @param languageWrittenIn Software language used to write the model, e.g. R or MatLab
 * @param modelCategory 
 * @param status The curation status of the model
 * @param objective Objective of the model or data
 * @param description General description of the study, data or model
 */
data class GenericModelGeneralInformation (

    /* A name given to the model or data */
    val name: kotlin.String,
    /* A source from which the model/data is derived */
    val source: kotlin.String? = null,
    /* An unambiguous ID given to the model or data. This can also be created automatically by a software tool */
    val identifier: kotlin.String,
    /* Person(s) who generated the model code or generated the data set originally */
    val author: kotlin.Array<Contact>? = null,
    /* The person(s) that created this FSK file including all metadata */
    val creator: kotlin.Array<Contact>? = null,
    /* Creation date/time of the FSK file */
    val creationDate: java.time.LocalDate,
    /* Date/time of the last version of the FSK file */
    val modificationDate: kotlin.Array<java.time.LocalDate>? = null,
    /* Rights granted for usage, distribution and modification of this FSK file */
    val rights: kotlin.String,
    /* Availability of data or model, i.e. if the annotated model code / data is included in this FSK file */
    val availability: kotlin.String? = null,
    /* Web address referencing the resource location (data for example) */
    val url: kotlin.String? = null,
    /* File extension of the model or data file (including version number of format if applicable) */
    val format: kotlin.String? = null,
    val reference: kotlin.Array<Reference>,
    /* A language of the resource (some data or reports can be available in French language for example) */
    val language: kotlin.String? = null,
    /* The program or software language in which the model has been implemented */
    val software: kotlin.String? = null,
    /* Software language used to write the model, e.g. R or MatLab */
    val languageWrittenIn: kotlin.String? = null,
    val modelCategory: ModelCategory? = null,
    /* The curation status of the model */
    val status: kotlin.String? = null,
    /* Objective of the model or data */
    val objective: kotlin.String? = null,
    /* General description of the study, data or model */
    val description: kotlin.String? = null
) {
}