/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param type General classification of the hazard for which the model or data applies
 * @param name Name of the hazard (agent, contaminant, chemical) for which the data or model applies
 * @param description Description of the hazard for which the model or data applies
 * @param unit Unit of the hazard for which the model or data applies
 * @param adverseEffect Adverse effect induced by hazard about morbidity, mortality, and etcetera
 * @param sourceOfContamination Origin of the contamination, source
 * @param benchmarkDose A dose or concentration that produces a predetermined change in response rate of an adverse effect (called the benchmark response or BMR) compared to background
 * @param maximumResidueLimit International regulations and permissible maximum residue levels in food and drinking water
 * @param noObservedAdverseAffectLevel Level of exposure of an organism, found by experiment or observation, at which there is no biologically or statistically significant increase in the frequency or severity of any adverse effects in the exposed population when compared to its appropriate control
 * @param lowestObservedAdverseAffectLevel Lowest concentration or amount of a substance found by experiment or observation that causes an adverse alteration of morphology, function, capacity, growth, development, or lifespan of a target organism distinguished from normal organisms of the same species under defined conditions of exposure
 * @param acceptableOperatorsExposureLevel Maximum amount of active substance to which the operator may be exposed without any adverse health effects. The AOEL is expressed as milligrams of the chemical per kilogram body weight of the operator
 * @param acuteReferenceDose An estimate (with uncertainty spanning perhaps an order of magnitude) of a daily oral exposure for an acute duration (24 hours or less) to the human population (including sensitive subgroups) that is likely to be without an appreciable risk of deleterious effects during a lifetime
 * @param acceptableDailyIntake Measure of amount of a specific substance in food or in drinking water tahta can be ingested (orally) on a daily basis over a lifetime without an appreciable health risk
 * @param indSum Define if the parameter reported is an individual residue/analyte, a summed residue definition or part of a sum a summed residue definition
 */
data class Hazard (

    /* General classification of the hazard for which the model or data applies */
    val type: kotlin.String? = null,
    /* Name of the hazard (agent, contaminant, chemical) for which the data or model applies */
    val name: kotlin.String,
    /* Description of the hazard for which the model or data applies */
    val description: kotlin.String? = null,
    /* Unit of the hazard for which the model or data applies */
    val unit: kotlin.String? = null,
    /* Adverse effect induced by hazard about morbidity, mortality, and etcetera */
    val adverseEffect: kotlin.String? = null,
    /* Origin of the contamination, source */
    val sourceOfContamination: kotlin.String? = null,
    /* A dose or concentration that produces a predetermined change in response rate of an adverse effect (called the benchmark response or BMR) compared to background */
    val benchmarkDose: kotlin.String? = null,
    /* International regulations and permissible maximum residue levels in food and drinking water */
    val maximumResidueLimit: kotlin.String? = null,
    /* Level of exposure of an organism, found by experiment or observation, at which there is no biologically or statistically significant increase in the frequency or severity of any adverse effects in the exposed population when compared to its appropriate control */
    val noObservedAdverseAffectLevel: kotlin.String? = null,
    /* Lowest concentration or amount of a substance found by experiment or observation that causes an adverse alteration of morphology, function, capacity, growth, development, or lifespan of a target organism distinguished from normal organisms of the same species under defined conditions of exposure */
    val lowestObservedAdverseAffectLevel: kotlin.String? = null,
    /* Maximum amount of active substance to which the operator may be exposed without any adverse health effects. The AOEL is expressed as milligrams of the chemical per kilogram body weight of the operator */
    val acceptableOperatorsExposureLevel: kotlin.String? = null,
    /* An estimate (with uncertainty spanning perhaps an order of magnitude) of a daily oral exposure for an acute duration (24 hours or less) to the human population (including sensitive subgroups) that is likely to be without an appreciable risk of deleterious effects during a lifetime */
    val acuteReferenceDose: kotlin.String? = null,
    /* Measure of amount of a specific substance in food or in drinking water tahta can be ingested (orally) on a daily basis over a lifetime without an appreciable health risk */
    val acceptableDailyIntake: kotlin.String? = null,
    /* Define if the parameter reported is an individual residue/analyte, a summed residue definition or part of a sum a summed residue definition */
    val indSum: kotlin.String? = null
) {
}