/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Reference

/**
 * 
 * @param name A name given to the model equation
 * @param modelEquationClass Information on that helps to categorize model equations
 * @param reference 
 * @param modelEquation The pointer to the file that holds the software code (e.g. R-script)
 * @param modelHypothesis 
 */
data class ModelEquation (

    /* A name given to the model equation */
    val name: kotlin.String,
    /* Information on that helps to categorize model equations */
    val modelEquationClass: kotlin.String? = null,
    val reference: kotlin.Array<Reference>? = null,
    /* The pointer to the file that holds the software code (e.g. R-script) */
    val modelEquation: kotlin.String,
    val modelHypothesis: kotlin.Array<kotlin.String>? = null
) {
}