/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param modelClass Type of model according to RAKIP classification
 * @param modelSubClass 
 * @param modelClassComment Empty
 * @param basicProcess 
 */
data class ModelCategory (

    /* Type of model according to RAKIP classification */
    val modelClass: kotlin.String,
    val modelSubClass: kotlin.Array<kotlin.String>? = null,
    /* Empty */
    val modelClassComment: kotlin.String? = null,
    val basicProcess: kotlin.Array<kotlin.String>? = null
) {
}