/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Assay
import de.bund.bfr.metadata.swagger.Laboratory
import de.bund.bfr.metadata.swagger.Study
import de.bund.bfr.metadata.swagger.StudySample

/**
 * 
 * @param study 
 * @param studySample 
 * @param laboratory 
 * @param assay 
 */
data class OtherModelDataBackground (

    val study: Study,
    val studySample: kotlin.Array<StudySample>? = null,
    val laboratory: kotlin.Array<Laboratory>? = null,
    val assay: kotlin.Array<Assay>? = null
) {
}