/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Contact
import de.bund.bfr.metadata.swagger.ModelCategory
import de.bund.bfr.metadata.swagger.Reference

/**
 * 
 * @param name 
 * @param source 
 * @param identifier 
 * @param author 
 * @param creator 
 * @param creationDate 
 * @param modificationDate 
 * @param rights 
 * @param availability 
 * @param url 
 * @param format 
 * @param reference 
 * @param language 
 * @param software 
 * @param languageWrittenIn 
 * @param modelCategory 
 * @param status 
 * @param objective 
 * @param description 
 */
data class OtherModelGeneralInformation (

    val name: kotlin.String,
    val source: kotlin.String? = null,
    val identifier: kotlin.String,
    val author: kotlin.Array<Contact>? = null,
    val creator: kotlin.Array<Contact>? = null,
    val creationDate: java.time.LocalDate,
    val modificationDate: kotlin.Array<java.time.LocalDate>? = null,
    val rights: kotlin.String,
    val availability: kotlin.String? = null,
    val url: kotlin.String? = null,
    val format: kotlin.String? = null,
    val reference: kotlin.Array<Reference>,
    val language: kotlin.String? = null,
    val software: kotlin.String? = null,
    val languageWrittenIn: kotlin.String,
    val modelCategory: ModelCategory? = null,
    val status: kotlin.String? = null,
    val objective: kotlin.String? = null,
    val description: kotlin.String? = null
) {
}