/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param name Name of the population for which the model or data applies
 * @param targetPopulation Population of individual that we are interested in describing and making statistical inferences about
 * @param populationSpan 
 * @param populationDescription 
 * @param populationAge 
 * @param populationGender Description of the percentage of gender
 * @param bmi 
 * @param specialDietGroups 
 * @param patternConsumption 
 * @param region 
 * @param country 
 * @param populationRiskFactor 
 * @param season 
 */
data class PopulationGroup (

    /* Name of the population for which the model or data applies */
    val name: kotlin.String,
    /* Population of individual that we are interested in describing and making statistical inferences about */
    val targetPopulation: kotlin.String? = null,
    val populationSpan: kotlin.Array<kotlin.String>? = null,
    val populationDescription: kotlin.Array<kotlin.String>? = null,
    val populationAge: kotlin.Array<kotlin.String>? = null,
    /* Description of the percentage of gender */
    val populationGender: kotlin.String? = null,
    val bmi: kotlin.Array<kotlin.String>? = null,
    val specialDietGroups: kotlin.Array<kotlin.String>? = null,
    val patternConsumption: kotlin.Array<kotlin.String>? = null,
    val region: kotlin.Array<kotlin.String>? = null,
    val country: kotlin.Array<kotlin.String>? = null,
    val populationRiskFactor: kotlin.Array<kotlin.String>? = null,
    val season: kotlin.Array<kotlin.String>? = null
) {
}