/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param name 
 * @param description 
 * @param unit 
 * @param method 
 * @param packaging 
 * @param treatment 
 * @param originCountry 
 * @param originArea 
 * @param fisheriesArea 
 * @param productionDate 
 * @param expiryDate 
 */
data class PredictiveModelScopeProduct (

    val name: kotlin.String,
    val description: kotlin.String? = null,
    val unit: kotlin.String,
    val method: kotlin.Array<kotlin.String>? = null,
    val packaging: kotlin.Array<kotlin.String>? = null,
    val treatment: kotlin.Array<kotlin.String>? = null,
    val originCountry: kotlin.String? = null,
    val originArea: kotlin.String? = null,
    val fisheriesArea: kotlin.String? = null,
    val productionDate: java.time.LocalDate? = null,
    val expiryDate: java.time.LocalDate? = null
) {
}