/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger

import de.bund.bfr.metadata.swagger.Hazard
import de.bund.bfr.metadata.swagger.Product

/**
 * 
 * @param product 
 * @param hazard 
 * @param generalComment 
 * @param temporalInformation 
 * @param spatialInformation 
 */
data class ProcessModelScope (

    val product: kotlin.Array<Product>,
    val hazard: kotlin.Array<Hazard>,
    val generalComment: kotlin.String? = null,
    val temporalInformation: kotlin.String? = null,
    val spatialInformation: kotlin.Array<kotlin.String>? = null
) {
}