/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param sse Statistical values calculated to describe the performance of the model fitting procedure
 * @param mse Statistical values calculated to describe the performance of the model fitting procedure
 * @param rmse Statistical values calculated to describe the performance of the model fitting procedure
 * @param rsquared Statistical values calculated to describe the performance of the model fitting procedure
 * @param aic Statistical values calculated to describe the performance of the model fitting procedure
 * @param bic Statistical values calculated to describe the performance of the model fitting procedure
 * @param sensitivityAnalysis Description of the results of an sensitivity analysis, i.e. how independence assumptions are met or how variables will affect the output of model
 */
data class QualityMeasures (

    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val sse: java.math.BigDecimal? = null,
    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val mse: java.math.BigDecimal? = null,
    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val rmse: java.math.BigDecimal? = null,
    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val rsquared: java.math.BigDecimal? = null,
    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val aic: java.math.BigDecimal? = null,
    /* Statistical values calculated to describe the performance of the model fitting procedure */
    val bic: java.math.BigDecimal? = null,
    /* Description of the results of an sensitivity analysis, i.e. how independence assumptions are met or how variables will affect the output of model */
    val sensitivityAnalysis: kotlin.String? = null
) {
}