/**
 * RAKIP Generic model
 * TODO
 *
 * OpenAPI spec version: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package de.bund.bfr.metadata.swagger


/**
 * 
 * @param identifier A user defined identifier for the study
 * @param title A title for the Study
 * @param description A brief description of the study aims
 * @param designType The type of study design being employed
 * @param assayMeasurementType The measurement being observed in this assay
 * @param assayTechnologyType The technology being employed to observe this measurement
 * @param assayTechnologyPlatform The technology platform used
 * @param accreditationProcedureForTheAssayTechnology Accreditation procedure for the analytical method used
 * @param protocolName The name of the protocol, e.g.Extraction Protocol
 * @param protocolType The type of the protocol, preferably coming from an Ontology, e.g. Extraction Protocol
 * @param protocolDescription A description of the Protocol
 * @param protocolURI A URI to link out to a publication, web page, etc. describing the protocol.
 * @param protocolVersion The version of the protocol used, where applicable
 * @param protocolParametersName The parameters used when executing this protocol
 * @param protocolComponentsName The components used when carrying out this protocol
 * @param protocolComponentsType Description
 */
data class Study (

    /* A user defined identifier for the study */
    val identifier: kotlin.String? = null,
    /* A title for the Study */
    val title: kotlin.String,
    /* A brief description of the study aims */
    val description: kotlin.String? = null,
    /* The type of study design being employed */
    val designType: kotlin.String? = null,
    /* The measurement being observed in this assay */
    val assayMeasurementType: kotlin.String? = null,
    /* The technology being employed to observe this measurement */
    val assayTechnologyType: kotlin.String? = null,
    /* The technology platform used */
    val assayTechnologyPlatform: kotlin.String? = null,
    /* Accreditation procedure for the analytical method used */
    val accreditationProcedureForTheAssayTechnology: kotlin.String? = null,
    /* The name of the protocol, e.g.Extraction Protocol */
    val protocolName: kotlin.String? = null,
    /* The type of the protocol, preferably coming from an Ontology, e.g. Extraction Protocol */
    val protocolType: kotlin.String? = null,
    /* A description of the Protocol */
    val protocolDescription: kotlin.String? = null,
    /* A URI to link out to a publication, web page, etc. describing the protocol. */
    val protocolURI: kotlin.String? = null,
    /* The version of the protocol used, where applicable */
    val protocolVersion: kotlin.String? = null,
    /* The parameters used when executing this protocol */
    val protocolParametersName: kotlin.String? = null,
    /* The components used when carrying out this protocol */
    val protocolComponentsName: kotlin.String? = null,
    /* Description */
    val protocolComponentsType: kotlin.String? = null
) {
}